/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mencoba_cari_kerja_1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author fastabee
 */
public class donasi_perpus extends javax.swing.JFrame {

    /**
     * Creates new form donasi_perpus
     */
    public donasi_perpus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        s = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        don_nadon = new javax.swing.JTextField();
        don_nabuk = new javax.swing.JTextField();
        don_napel = new javax.swing.JTextField();
        don_tatel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 255, 255));
        jTextField1.setFont(new java.awt.Font("Forte", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Literasi Maju Untuk Indonesia Baru");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 330, 40));

        s.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        s.setForeground(new java.awt.Color(51, 51, 51));
        s.setText("Nama Donatur");
        getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nama Buku");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 80, -1));

        s1.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        s1.setForeground(new java.awt.Color(51, 51, 51));
        s1.setText("Nama Penulis");
        getContentPane().add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        s2.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        s2.setForeground(new java.awt.Color(51, 51, 51));
        s2.setText("Tahun Terbit");
        getContentPane().add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        don_nadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                don_nadonActionPerformed(evt);
            }
        });
        getContentPane().add(don_nadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 140, -1));
        getContentPane().add(don_nabuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 140, -1));
        getContentPane().add(don_napel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 140, -1));

        don_tatel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                don_tatelActionPerformed(evt);
            }
        });
        getContentPane().add(don_tatel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 140, -1));

        jButton1.setText("kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 204, 255));
        jButton2.setText("Donasi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 90, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\Background\\donasi buku.jpeg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void don_tatelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_don_tatelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_don_tatelActionPerformed

    private void don_nadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_don_nadonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_don_nadonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String Nama_Buku = don_nabuk.getText().toString().trim();
        String Nama_Penulis = don_napel.getText().toString().trim();
        String Tahun_Terbit = don_tatel.getText().toString().trim();
        String Nama_Donatur = don_nadon.getText().toString().trim();
        
        
        if (Nama_Donatur.equals("")){
            JOptionPane.showMessageDialog(null, "Nama donatur harus di isi meskipun nama alias demi optimalnya data");
        
        }else{
        try {
            Connection c = koneksi_register_semua.getkoneksi3();
            String sql = "INSERT INTO daftar_buku VALUES (?, ?, ?, ?)";
            PreparedStatement p = c.prepareCall(sql);
            p.setString(1, Nama_Buku);
            p.setString(2, Nama_Penulis);
            p.setString(3, Tahun_Terbit);
            p.setString(4, Nama_Donatur);
            p.executeUpdate();
            JOptionPane.showMessageDialog(null, "Terimkasih Sudah Mendonasikan Buku Anda");
            
            
            
        } catch (Exception e) {
            System.out.println("error");
        } finally{
           this.dispose();
           new Perpustakaan_Desa().setVisible(true); 
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Perpustakaan_Desa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(donasi_perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(donasi_perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(donasi_perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(donasi_perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new donasi_perpus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField don_nabuk;
    private javax.swing.JTextField don_nadon;
    private javax.swing.JTextField don_napel;
    private javax.swing.JTextField don_tatel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel s;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    // End of variables declaration//GEN-END:variables
}
