  /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mencoba_cari_kerja_1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static mencoba_cari_kerja_1.main_frame.selamatdatang;
import static mencoba_cari_kerja_1.main_frame.tampilkanid;

import static mencoba_cari_kerja_1.masuk_keluhan.kel_naleng;
import static mencoba_cari_kerja_1.masuk_keluhan.kel_nik;
import static mencoba_cari_kerja_1.pinjam_perpus.pin_nik;
import static mencoba_cari_kerja_1.tawarkan_diri.tawdi_nama;
import static mencoba_cari_kerja_1.tawarkan_diri.tawdi_nik;


/**
 *
 * @author fastabee
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        re_nik = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        log_password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Dubai Light", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LOGIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 120, 30));

        re_nik.setForeground(new java.awt.Color(51, 51, 51));
        re_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re_nikActionPerformed(evt);
            }
        });
        getContentPane().add(re_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 170, 30));

        jLabel4.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Belum punya akun ? ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        log_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(log_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 170, 30));

        jLabel7.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 153));
        jLabel7.setText("Daftar");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\Background\\login.jpeg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 420));

        setSize(new java.awt.Dimension(517, 460));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            Connection c = koneksi_register.getkoneksi1();
            Statement s = c.createStatement();
            
            String sql = "SELECT * FROM login Where NIK ='" + re_nik.getText()
                    +"' and password = '"+ log_password.getText()+ "'";
            ResultSet r = s.executeQuery(sql);
            
            
            
            if (r.next()){
                JOptionPane.showMessageDialog(null, "login berhasil");
                new main_frame().setVisible(true);
                this.dispose();
                pin_nik.setText(r.getString(2));
                selamatdatang.setText("Selamat Datang " + '"'+r.getString(3)+'"');
                tampilkanid.setText(r.getString(2));
                tawdi_nik.setText(r.getString(2));
                tawdi_nama.setText(r.getString(3));
                kel_nik.setText(r.getString(2));
                kel_naleng.setText(r.getString(3));
               
                
                
                
                
            }
            
            else {
            JOptionPane.showMessageDialog(null, "username atau password salah");
            log_password.requestFocus();
            }
            
            } catch (SQLException e) {
            System.out.println("error");
            }
               
    }//GEN-LAST:event_jButton2ActionPerformed

    private void log_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_log_passwordActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        new register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void re_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_re_nikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField log_password;
    private javax.swing.JTextField re_nik;
    // End of variables declaration//GEN-END:variables
}
