 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mencoba_cari_kerja_1;

/**
 *
 * @author fastabee
 * 
 */

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
public class pinjam_perpus extends javax.swing.JFrame {

 private DefaultTableModel tabmode3;
    
    private void tampil_buku(){
    Object[]baris2 = {"Judul", "Penulis", "Terbitan","Donatur"};
    tabmode3 = new DefaultTableModel(null, baris2);
    buku_tersedia.setModel(tabmode3);
    String cari = kolom_cari.getText();
    String sql = "SELECT * FROM daftar_buku WHERE Nama_Buku LIKE'%"+cari+"%'";
    
    
        try {
          Connection konek = new koneksi_tabel().getConnection();
          Statement stat = konek.createStatement();
          ResultSet hasil = stat.executeQuery(sql);
          while(hasil.next()){
          String Nama_Lengkap = hasil.getString("Nama_Buku");
          String Nama_Orang_Tua = hasil.getString("Nama_Penulis");
          String Alamat = hasil.getString("Tahun_Terbit");
          String Nomor_Telepon = hasil.getString("Nama_Donatur");
          String[]data3 = {Nama_Lengkap, Nama_Orang_Tua, Alamat, Nomor_Telepon};
          tabmode3.addRow(data3);
          
          }
          konek.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "koneksi gagal", "informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    
    
    
    
    }
    
    public pinjam_perpus() {
        initComponents();
        tampil_buku();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        buku_tersedia = new javax.swing.JTable();
        kolom_cari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pin_nadon = new javax.swing.JTextField();
        pin_nabuk = new javax.swing.JTextField();
        pin_napel = new javax.swing.JTextField();
        pin_tatel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pin_tankem = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buku_tersedia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        buku_tersedia.setEnabled(false);
        buku_tersedia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buku_tersediaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(buku_tersedia);
        if (buku_tersedia.getColumnModel().getColumnCount() > 0) {
            buku_tersedia.getColumnModel().getColumn(2).setResizable(false);
            buku_tersedia.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 290, 90));

        kolom_cari.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        kolom_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolom_cariActionPerformed(evt);
            }
        });
        kolom_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kolom_cariKeyReleased(evt);
            }
        });
        getContentPane().add(kolom_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 105, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setText("Pinjam");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 70, 40));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel2.setText("Nama_Donatur");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel3.setText("Nama_Buku");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel4.setText("Nama_Penulis");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel5.setText("Tahun_Terbit");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        pin_nadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pin_nadonActionPerformed(evt);
            }
        });
        getContentPane().add(pin_nadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 130, -1));
        getContentPane().add(pin_nabuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 130, -1));
        getContentPane().add(pin_napel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 130, -1));
        getContentPane().add(pin_tatel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 130, -1));

        jLabel8.setText("silahkan klik dua kali pada kolom tabel !!!!!");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 310, -1));

        jButton3.setText("kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, 40));
        getContentPane().add(pin_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 130, -1));

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel6.setText("Nik");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 110, -1));

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel7.setText("Tanggal_Kembali");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(pin_tankem, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\Background\\blok buku.jpeg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // TODO add your handling code here:
         
             
        
        String Nik = pin_nik.getText().toString().trim();
        String Tanggal_Kembali = pin_tankem.getDate().toString().trim();
        String Nama_Buku = pin_nabuk.getText().toString().trim();
        String Nama_penulis = pin_napel.getText().toString().trim();
        String Tahun_Terbit = pin_tatel.getText().toString().trim();
        String Nama_Donatur =pin_nadon.getText().toString().trim();
        
               
       
       try {
             Connection c = koneksi_register_semua.getkoneksi3();
             String sql = "INSERT INTO detil_pinjam_buku1 VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement p = c.prepareCall(sql);
            p.setString(1, Nik);
            p.setString(2, Tanggal_Kembali);
            p.setString(3, Nama_Buku);
            p.setString(4, Nama_penulis);
            p.setString(5, Tahun_Terbit);
            p.setString(6, Nama_Donatur);
            p.executeUpdate();
            JOptionPane.showMessageDialog(null, "Peminjaman Berhasil, Silahkan ambil bukti peminjaman anda");
                  
            
            String reportSource = null;
            String reportDest = null;
            reportSource = System.getProperty("user.dir")+ "/src/bukti_pinjam_perpus.jrxml";
            reportDest = System.getProperty("user.dir")+ "/src/bukti_pinjam_perpus.jasper";
            HashMap hp = new HashMap();
            hp.put("nik", String.valueOf(pin_nik.getText()));
            
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hp, c);
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint, false);
               
            } catch (Exception e) {
                System.out.println(e);
            }
       

        
    
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void kolom_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kolom_cariKeyReleased
        // TODO add your handling code here:
        tampil_buku();
    }//GEN-LAST:event_kolom_cariKeyReleased

    private void pin_nadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pin_nadonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pin_nadonActionPerformed

    private void buku_tersediaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buku_tersediaMouseClicked
        // TODO add your handling code here:
        int barisnya = buku_tersedia.rowAtPoint(evt.getPoint());
        
        String nb = buku_tersedia.getValueAt(barisnya, 0).toString();
        pin_nabuk.setText(nb);
        String np = buku_tersedia.getValueAt(barisnya, 1).toString();
        pin_napel.setText(np);
        String tt = buku_tersedia.getValueAt(barisnya, 2).toString();
        pin_tatel.setText(tt);
        String nd = buku_tersedia.getValueAt(barisnya, 3).toString();
        pin_nadon.setText(nd);
        
    }//GEN-LAST:event_buku_tersediaMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
           try{
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/cari_kerja","root","");
        cn.createStatement().executeUpdate("delete from daftar_buku where Nama_Buku ='"+pin_nabuk.getText()+"'");
        tampil_buku();
        }
        catch(Exception e){
            System.out.println("masih error");
        }finally {
           this.dispose();
           new Perpustakaan_Desa().setVisible(true);
           }
        
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void kolom_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolom_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolom_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pinjam_perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pinjam_perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pinjam_perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pinjam_perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pinjam_perpus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable buku_tersedia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kolom_cari;
    private javax.swing.JTextField pin_nabuk;
    private javax.swing.JTextField pin_nadon;
    private javax.swing.JTextField pin_napel;
    public static final javax.swing.JTextField pin_nik = new javax.swing.JTextField();
    private com.toedter.calendar.JDateChooser pin_tankem;
    private javax.swing.JTextField pin_tatel;
    // End of variables declaration//GEN-END:variables
}
