/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mencoba_cari_kerja_1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author fastabee
 */
public class register extends javax.swing.JFrame {
    
    
    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        
       
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        re_id = new javax.swing.JTextField();
        re_username = new javax.swing.JTextField();
        re_password = new javax.swing.JPasswordField();
        re_Con_password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        re_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re_idActionPerformed(evt);
            }
        });
        getContentPane().add(re_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 130, -1));
        getContentPane().add(re_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 130, -1));

        re_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(re_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 130, -1));

        re_Con_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re_Con_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(re_Con_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 130, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setText("DAFTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 120, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\Background\\Register.jpeg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 430));

        setSize(new java.awt.Dimension(516, 458));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void re_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_re_passwordActionPerformed

    private void re_Con_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re_Con_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_re_Con_passwordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String NIK = re_id.getText().toString().trim();
        String Username = re_username.getText().toString().trim();
        String Password = re_password.getText().toString().trim();
        String Conpassword = re_Con_password.getText().toString().trim();

        
        if (!Password.equals (Conpassword)){
            JOptionPane.showMessageDialog(null, "password tidak sama");
             
        }
        else if (Password.equals("") || Username.equals("")){
       JOptionPane.showMessageDialog(null, "username atau password tidak boleh kosong");
    } 
        else {
            try {
                Connection c = koneksi_register.getkoneksi1();
                String sql = "INSERT INTO login  VALUES (?, ?, ?) ";
                PreparedStatement p  = c.prepareStatement(sql);
                p.setString(1, NIK);
                p.setString(2, Username);
                p.setString(3, Password);
                p.executeUpdate();  
                JOptionPane.showMessageDialog(null, "pembuatan akun sukses");
                
                
                
                
                
            } catch (Exception e) {
                System.out.println("error" );
            } finally{
             this.dispose();
             new Login().setVisible(true);
             
        }
        
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void re_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_re_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPasswordField re_Con_password;
    private javax.swing.JTextField re_id;
    private javax.swing.JPasswordField re_password;
    private javax.swing.JTextField re_username;
    // End of variables declaration//GEN-END:variables
}
